# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 06:34
from __future__ import unicode_literals

import Accessories.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0006_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, default='99.99', max_digits=10)),
                ('condition', models.CharField(choices=[('used', 'Used'), ('new', 'New')], max_length=4)),
                ('category', models.CharField(choices=[('hat', 'Hat'), ('tie', 'Tie'), ('purse', 'Purse'), ('brooch', 'Brooch'), ('jewellery', 'Jewellery'), ('wig', 'Wig')], max_length=17)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('sold', models.BooleanField(default=False)),
                ('image1', models.ImageField(upload_to=Accessories.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=Accessories.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=Accessories.models.upload_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=Accessories.models.upload_image_path)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.Profile')),
            ],
            options={
                'db_table': 'Accessories',
            },
        ),
    ]
