# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='category',
            field=models.CharField(choices=[('cap', 'Cap'), ('tie', 'Tie'), ('purse', 'Purse'), ('brooch', 'Brooch'), ('jewellery', 'Jewellery'), ('wig', 'Wig')], max_length=17),
        ),
    ]
