# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0002_auto_20190208_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
